name: Build and Deploy Vue to MonsterASP.NET

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Válaszd a megfelelő verziót

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Ha Vite-et használsz, akkor npm run build lehet szükséges

      - name: Deploy to MonsterASP.NET via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ # Ha a build kimenete máshol van, módosítsd
          server-dir: /wwwroot/ # Módosítsd az ASP.NET tárhely beállításai szerint